name: Publish
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: write
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
          - os: ubuntu-24.04
            platform: android
            arch: x64
          - os: ubuntu-24.04
            platform: android
            arch: ia32
          - os: ubuntu-24.04
            platform: android
            arch: arm64
          - os: ubuntu-24.04
            platform: android
            arch: arm
          - os: macos-14
            platform: darwin
            arch: x64
          - os: macos-14
            platform: darwin
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
          - os: macos-14
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
          - os: windows-2022
            platform: win32
            arch: x64
          - os: windows-2022
            platform: win32
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build / ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: ${{ matrix.flags }}
          tags: ${{ matrix.tags}}
          upload: true
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    needs: prebuild
    name: Publish
    steps:
      - uses: holepunchto/actions/node-base@v1
      - uses: holepunchto/actions/download-prebuilds@v1
      - uses: holepunchto/actions/publish@v1
